spring:
  application:
    name: gateway

server:
  port: 9010

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
