server:
  port: 8090
spring:
  application:
    name: session-redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root123
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
