eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 9093
spring:
  application:
    name: service-hi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:Mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9092:/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:9092/oauth/token
      grant-type: client_credentials,password
      scope: server
